### ISSUE TITLE
Word Wrap?

### ISSUE THREAD

**Issue by that1estonian** [tjenkinson/dynamic-marquee#222]
How does one word wrap, when doing up/down scrolling? :roll_eyes:

**Comment by tjenkinson** [comment]
As long as the thing you are putting in the marquee has a fixed width it should be fine?

**Comment by that1estonian** [comment]
```html
<div class="endScreenWrapper" id="endScreenWrapper">
    <span id="endScreen"></span>
</div>
```

```css
.endScreenWrapper {
    width: 1920px;
    height: 1080px;
    top: 0px;
    left: 0px;
    display: none;
    text-align: center;
    font-size: 90px;
}
```

```javascript
endScreen.appendItem("Lorem Ipsum is simply dummy text of the printing and typesetting industry...");
```

:man_shrugging:

**Comment by tjenkinson** [comment]
Please can you provide the complete code you’re using where you construct the marquee?

**Comment by that1estonian** [comment]
> Please can you provide the complete code you’re using where you construct the marquee?

```css
.endScreenWrapper {
    width: 1920px;
    height: 1080px;
    top: 0px;
    left: 0px;
    display: block;
    text-align: center;
    font-size: 90px;
}
```

```html
<div class="endScreenWrapper" id="endScreenWrapper">
    <span id="endScreen"></span>
</div>
```

```javascript
import { Marquee } from 'dynamic-marquee';

const endScreen = new Marquee(document.getElementById('endScreen'), {
    rate: -90,
    upDown: true
});

endScreen.appendItem("Lorem Ipsum is simply dummy text of the printing and typesetting industry...");
```
